name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          npm install
          npm run lint
          #npm run test
          npm run build

      - uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: logs
          path: /home/runner/.npm/_logs/*.log

      - name: Publish docs to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: master
          build_dir: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
